# Generated by Django 5.1.7 on 2025-03-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'request in progress'), ('completed', 'request completed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('result_path', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type', models.CharField(choices=[('nanopore', 'Nanopore'), ('illumina', 'Illumina')], max_length=20)),
                ('data_arch_path', models.CharField(max_length=255)),
                ('adapter', models.CharField(blank=True, max_length=255, null=True)),
                ('classifier', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_seq', models.CharField(max_length=255)),
                ('ref_database', models.CharField(max_length=255)),
                ('minlen', models.IntegerField(default=150)),
                ('maxns', models.IntegerField(default=5)),
                ('maxee', models.FloatField(default=2.0)),
                ('min_quality', models.IntegerField(default=20)),
                ('max_ambiguous', models.IntegerField(default=2)),
                ('trim_left', models.IntegerField(default=80)),
                ('trim_right', models.IntegerField(default=700)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_params', to='data_processing.request')),
            ],
        ),
    ]
