# Generated by Django 5.1.8 on 2025-04-02 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Request in progress'), ('completed', 'Request completed')], default='in_progress', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('result_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Result path')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type', models.CharField(choices=[('nanopore', 'Nanopore'), ('illumina', 'Illumina')], max_length=20, verbose_name='Pipeline type')),
                ('data_arch_path', models.CharField(max_length=255, verbose_name='Data archive path')),
                ('adapter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adapter')),
                ('classifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Classifier')),
                ('ref_seq', models.CharField(max_length=255, verbose_name='Reference sequence')),
                ('ref_database', models.CharField(max_length=255, verbose_name='Reference database')),
                ('minlen', models.IntegerField(default=150, verbose_name='Minimum length')),
                ('maxns', models.IntegerField(default=5, verbose_name='Maximum Ns')),
                ('maxee', models.FloatField(default=2.0, verbose_name='Maximum expected errors')),
                ('min_quality', models.IntegerField(default=20, verbose_name='Minimum quality')),
                ('max_ambiguous', models.IntegerField(default=2, verbose_name='Maximum ambiguous bases')),
                ('trim_left', models.IntegerField(default=80, verbose_name='Trim left')),
                ('trim_right', models.IntegerField(default=700, verbose_name='Trim right')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_params', to='data_processing.request', verbose_name='Request')),
            ],
            options={
                'verbose_name': 'Pipeline Parameters',
                'verbose_name_plural': 'Pipeline Parameters',
            },
        ),
    ]
